name: asm-cpu6502
version: '0.5.0'
synopsis: The 6502 Cpu specific parts of the assembler
category: Compilers/Interpreters
author: ALeX Kazik
maintainer: alex@kazik.de
copyright: 2017 ALeX Kazik
license: BSD3
homepage: https://github.com/alexkazik/asm
dependencies:
- asm-core ==0.5.0
- asm-data ==0.5.0
- asm-parser ==0.5.0
- base >=4.9
- containers
- extra
- heredoc
- syb
- template-haskell
- text
- vector
library:
  source-dirs: src
  ghc-options: -Wall
