name: asm-cpu6809
version: '0.6.0'
synopsis: The 6809 Cpu specific parts of the assembler
category: Compilers/Interpreters
author: ALeX Kazik
maintainer: alex@kazik.de
copyright: 2017 ALeX Kazik
license: BSD3
homepage: https://github.com/alexkazik/asm
dependencies:
- asm-core ==0.6.0
- asm-data ==0.6.0
- asm-parser ==0.6.0
- base >=4.9
- containers
- extra
- heredoc
- syb
- template-haskell
- text
- vector
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Asm.Cpu6809
  - Asm.Cpu6809.Compiler.Function
  - Asm.Cpu6809.Compiler.Phase2
  - Asm.Cpu6809.Compiler.Phase3
  - Asm.Cpu6809.Compiler.Phase4
  - Asm.Cpu6809.Compiler.Phase5
  - Asm.Cpu6809.Data.Cpu6809
  - Asm.Cpu6809.Data.CpuData6809
  - Asm.Cpu6809.Data.CpuSource6809
  - Asm.Cpu6809.Data.FunctionKey
  - Asm.Cpu6809.Data.MetaKey
  - Asm.Cpu6809.Data.OpCodes
  - Asm.Cpu6809.OpCodes.Generator
  - Asm.Cpu6809.OpCodes.Parser
  - Asm.Cpu6809.OpCodes.Quote
  - Asm.Cpu6809.Parser
  - Asm.Cpu6809.Parser.CpuStmt
  - Asm.Cpu6809.Suffixed
