name: demo
version: '0.5.0'
synopsis: A few demo programs using the assembler
category: Compilers/Interpreters
author: ALeX Kazik
maintainer: alex@kazik.de
copyright: 2017 ALeX Kazik
license: BSD3
homepage: https://github.com/alexkazik/asm
dependencies:
- base
- bytestring
library:
  source-dirs: src
  ghc-options: -Wall
  dependencies:
  - asm-core ==0.5.0
  - asm-c64 ==0.5.0
  - asm-cpu6809 ==0.5.0
  - asm-cpu6502 ==0.5.0
  - heredoc
  - text
  - vector
executables:
  demo-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - demo
    - directory
    - filepath
    - optparse-applicative
