name: asm-c64
version: '0.5.0'
synopsis: Files specific to the C64 platform
category: Compilers/Interpreters
author: ALeX Kazik
maintainer: alex@kazik.de
copyright: 2017 ALeX Kazik
license: BSD3
homepage: https://github.com/alexkazik/asm
dependencies:
- asm-core ==0.5.0
- asm-data ==0.5.0
- asm-parser ==0.5.0
- asm-tools ==0.5.0
- asm-cpu6502 ==0.5.0
- base
- bytestring
- containers
- JuicyPixels
- syb
- template-haskell
- text
- vector
library:
  source-dirs: src
  ghc-options: -Wall
