name: asm-data
version: '0.6.0'
synopsis: Data structures used by the assembler but not specific to it
category: Compilers/Interpreters
author: ALeX Kazik
maintainer: alex@kazik.de
copyright: 2017 ALeX Kazik
license: BSD3
homepage: https://github.com/alexkazik/asm
dependencies:
- base >=4.9
- bytestring
- mtl
- transformers
library:
  source-dirs: src
  ghc-options: -Wall
  other-modules:
  - Asm.Data.Control.Monad.Error.Class
  - Asm.Data.Control.Monad.Error.Internal
  - Asm.Data.Ternary.Internal
